 
 **Numpy Tutorials**
       NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and     tools for working with these arrays. It is the fundamental package for scientific computing with Python

**What is an array**

An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [4]:
import numpy as np

In [7]:
lst = [1,2,3,4,5]
arr = np.array(lst)

In [8]:
print(arr)

[1 2 3 4 5]


In [9]:
type(arr)

numpy.ndarray

In [10]:
arr

array([1, 2, 3, 4, 5])

In [11]:
arr.shape

(5,)

In [17]:
lst1 = [1,2,3,4,5]
lst2 = [6,7,8,9,10]
lst3 = [11,12,13,14,15]

lst = [lst1,lst2,lst3]
lst
arr = np.array([lst1,lst2,lst3])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [18]:
#check the shape of the array
arr.shape

(3, 5)

In [22]:
arr1 = arr.reshape(5,3)
arr1


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

<b> Indexing

In [23]:
#accessing elements\
arr = np.array([1,2,3,4,5,6,7,8])
arr[3]

4

In [24]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [26]:
lst1 = [1,2,3,4,5]
lst2 = [6,7,8,9,10]
lst3 = [11,12,13,14,15]

lst = [lst1,lst2,lst3]
lst
arr = np.array([lst1,lst2,lst3])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [32]:
arr[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [33]:
arr[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [35]:
arr[1:3,3:5]

array([[ 9, 10],
       [14, 15]])

In [50]:
arrn = np.arange(0,10,step =1)
arrn

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.linspace(1,10,50) #gives 50 points b/w 1 and 10.

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [51]:
#copy() and broadcasting

arrn[3:] = 100
arrn

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [52]:
arr1 = arrn
arr1[3:] = 500
arr1

array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500])

In [53]:
arrn #this is also updated bcoz array is reference type 

array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500])

In [54]:
arr1 = arrn.copy() # this makes an aanother vopy of this in diffrent mem locztion

In [55]:
print(arrn)
arr1[3:] = 1000
print(arr1)

[  0   1   2 500 500 500 500 500 500 500]
[   0    1    2 1000 1000 1000 1000 1000 1000 1000]


In [57]:

### Some conditions very useful in Exploratory Data Analysis 
val =2
print(arrn<2)
print(arrn*2)
print(arrn/2)

[ True  True False False False False False False False False]
[   0    2    4 1000 1000 1000 1000 1000 1000 1000]
[  0.    0.5   1.  250.  250.  250.  250.  250.  250.  250. ]


In [58]:
arrn[arrn<300]

array([0, 1, 2])

In [60]:
np.ones(4 , dtype = int)

array([1, 1, 1, 1])

In [62]:
np.ones((2,5),dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [65]:
##randome distribution
np.random.rand(3)  #gives randome values from 0 to 1

array([0.17797893, 0.89869948, 0.27296972])

In [67]:
arr_ex = np.random.randn(4,4) #Return a sample (or samples) from the "standard normal" distribution.
arr_ex

array([[-0.81112904,  2.34102649,  0.08141813,  0.21361925],
       [-1.11685375, -0.10029278,  1.54900478,  0.54707674],
       [-1.59287399, -1.00120134,  0.14479668, -0.75675085],
       [ 1.42844688,  1.03070371,  0.12890727,  0.07369666]])

In [68]:
np.random.randint(0,100,8)

array([92, 91, 18, 42, 32, 30, 35, 58])

In [71]:
np.random.random_sample((1,5))

array([[0.74466871, 0.25536168, 0.63301197, 0.62176593, 0.11454421]])